defmodule Openats.Repo.Migrations.AddPositionProfiles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:postion_openings) do
      add :position_profile_id, :uuid
    end

    create table(:position_openings, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
    end

    alter table(:postion_openings) do
      modify :position_profile_id,
             references(:position_openings,
               column: :id,
               prefix: "public",
               name: "postion_openings_position_profile_id_fkey",
               type: :uuid
             )
    end

    alter table(:position_openings) do
      add :name, :text, null: false
      add :description, :text, null: false
      add :qualifications, {:array, :text}
    end
  end

  def down do
    alter table(:position_openings) do
      remove :qualifications
      remove :description
      remove :name
    end

    drop constraint(:postion_openings, "postion_openings_position_profile_id_fkey")

    alter table(:postion_openings) do
      modify :position_profile_id, :uuid
    end

    drop table(:position_openings)

    alter table(:postion_openings) do
      remove :position_profile_id
    end
  end
end