defmodule Openats.Repo.Migrations.AddCandidateAndPerson do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:people, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :name, :text, null: false
    end

    create table(:candidates, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :status, :text, null: false, default: "active"

      add :position_opening_id,
          references(:postion_openings,
            column: :id,
            name: "candidates_position_opening_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :person_id,
          references(:people,
            column: :id,
            name: "candidates_person_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:candidates, "candidates_person_id_fkey")

    drop constraint(:candidates, "candidates_position_opening_id_fkey")

    drop table(:candidates)

    drop table(:people)
  end
end