defmodule Openats.Repo.Migrations.AddPositionOpenings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:postion_openings, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :name, :text, null: false
      add :status, :text, null: false, default: "active"
    end
  end

  def down do
    drop table(:postion_openings)
  end
end